name: publish

on:
  release:
    types: [published]
    
jobs:
  publish:
  
    name: Publish to PyPi
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Setuptools
        run: |
          python -m pip install setuptools
      - name: Install wheel
        run: |
          python -m pip install wheel
      - name: Build
        run: |
          python setup.py install bdist_wheel
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.PYPI_API_TOKEN}}